# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bstats.proto\"\x83\x04\n\tPortStats\x12\t\n\x01n\x18\x01 \x02(\x04\x12\r\n\x05n_rtt\x18\x02 \x02(\x04\x12\x0c\n\x04port\x18\x03 \x02(\x04\x12\x11\n\tavg_rxpps\x18\x04 \x02(\x01\x12\x11\n\tvar_rxpps\x18\x05 \x02(\x01\x12\x11\n\tavg_rxbps\x18\x06 \x02(\x01\x12\x11\n\tvar_rxbps\x18\x07 \x02(\x01\x12\x11\n\tavg_txpps\x18\x08 \x02(\x01\x12\x11\n\tvar_txpps\x18\t \x02(\x01\x12\x11\n\tavg_txbps\x18\n \x02(\x01\x12\x11\n\tvar_txbps\x18\x0b \x02(\x01\x12\x12\n\navg_txwire\x18\x0c \x02(\x01\x12\x12\n\nvar_txwire\x18\r \x02(\x01\x12\x12\n\navg_rxwire\x18\x0e \x02(\x01\x12\x12\n\nvar_rxwire\x18\x0f \x02(\x01\x12\x0f\n\x07rtt_avg\x18\x10 \x02(\x01\x12\x0f\n\x07rtt_std\x18\x11 \x02(\x01\x12\r\n\x05rtt_0\x18\x12 \x02(\x01\x12\x0e\n\x06rtt_25\x18\x13 \x02(\x01\x12\x0e\n\x06rtt_50\x18\x14 \x02(\x01\x12\x0e\n\x06rtt_75\x18\x15 \x02(\x01\x12\x0e\n\x06rtt_90\x18\x16 \x02(\x01\x12\x0e\n\x06rtt_95\x18\x17 \x02(\x01\x12\x0e\n\x06rtt_99\x18\x18 \x02(\x01\x12\x0f\n\x07rtt_100\x18\x19 \x02(\x01\x12\x10\n\x08tx_bytes\x18\x1a \x02(\x04\x12\x0f\n\x07tx_pkts\x18\x1b \x02(\x04\x12\x10\n\x08rx_bytes\x18\x1c \x02(\x04\x12\x0f\n\x07rx_pkts\x18\x1d \x02(\x04\"\"\n\x05Stats\x12\x19\n\x05stats\x18\x01 \x03(\x0b\x32\n.PortStats')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PORTSTATS = _descriptor.Descriptor(
  name='PortStats',
  full_name='PortStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='PortStats.n', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_rtt', full_name='PortStats.n_rtt', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='PortStats.port', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_rxpps', full_name='PortStats.avg_rxpps', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_rxpps', full_name='PortStats.var_rxpps', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_rxbps', full_name='PortStats.avg_rxbps', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_rxbps', full_name='PortStats.var_rxbps', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_txpps', full_name='PortStats.avg_txpps', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_txpps', full_name='PortStats.var_txpps', index=8,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_txbps', full_name='PortStats.avg_txbps', index=9,
      number=10, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_txbps', full_name='PortStats.var_txbps', index=10,
      number=11, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_txwire', full_name='PortStats.avg_txwire', index=11,
      number=12, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_txwire', full_name='PortStats.var_txwire', index=12,
      number=13, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_rxwire', full_name='PortStats.avg_rxwire', index=13,
      number=14, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_rxwire', full_name='PortStats.var_rxwire', index=14,
      number=15, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_avg', full_name='PortStats.rtt_avg', index=15,
      number=16, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_std', full_name='PortStats.rtt_std', index=16,
      number=17, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_0', full_name='PortStats.rtt_0', index=17,
      number=18, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_25', full_name='PortStats.rtt_25', index=18,
      number=19, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_50', full_name='PortStats.rtt_50', index=19,
      number=20, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_75', full_name='PortStats.rtt_75', index=20,
      number=21, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_90', full_name='PortStats.rtt_90', index=21,
      number=22, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_95', full_name='PortStats.rtt_95', index=22,
      number=23, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_99', full_name='PortStats.rtt_99', index=23,
      number=24, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_100', full_name='PortStats.rtt_100', index=24,
      number=25, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_bytes', full_name='PortStats.tx_bytes', index=25,
      number=26, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_pkts', full_name='PortStats.tx_pkts', index=26,
      number=27, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_bytes', full_name='PortStats.rx_bytes', index=27,
      number=28, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_pkts', full_name='PortStats.rx_pkts', index=28,
      number=29, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=531,
)


_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='Stats.stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=567,
)

_STATS.fields_by_name['stats'].message_type = _PORTSTATS
DESCRIPTOR.message_types_by_name['PortStats'] = _PORTSTATS
DESCRIPTOR.message_types_by_name['Stats'] = _STATS

PortStats = _reflection.GeneratedProtocolMessageType('PortStats', (_message.Message,), dict(
  DESCRIPTOR = _PORTSTATS,
  __module__ = 'stats_pb2'
  # @@protoc_insertion_point(class_scope:PortStats)
  ))
_sym_db.RegisterMessage(PortStats)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), dict(
  DESCRIPTOR = _STATS,
  __module__ = 'stats_pb2'
  # @@protoc_insertion_point(class_scope:Stats)
  ))
_sym_db.RegisterMessage(Stats)


# @@protoc_insertion_point(module_scope)
